"""Summarize OpenAI Batch frame-QA results for Track B.

This merges a Batch API output `.jsonl` file with the request manifest
generated by `build_track_b_openai_batch.py` and produces:

- a merged CSV with per-frame QA fields
- a markdown summary
- an optional relabel priority CSV sorted by the combined score
"""
from __future__ import annotations

import argparse
import csv
import json
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any


def _read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def _parse_json_maybe(text: str) -> dict[str, Any]:
    return json.loads(text)


def _extract_output_text(body: dict[str, Any]) -> str:
    output_text = body.get("output_text")
    if isinstance(output_text, str) and output_text.strip():
        return output_text

    for item in body.get("output", []) or []:
        if not isinstance(item, dict):
            continue
        for content in item.get("content", []) or []:
            if not isinstance(content, dict):
                continue
            text = content.get("text")
            if isinstance(text, str) and text.strip():
                return text
    raise ValueError("No output text found in batch response body.")


def _load_results(path: Path) -> dict[str, dict[str, Any]]:
    results: dict[str, dict[str, Any]] = {}
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            record = json.loads(line)
            custom_id = record.get("custom_id")
            if not custom_id:
                continue

            error = record.get("error")
            response = record.get("response") or {}
            status_code = response.get("status_code")
            body = response.get("body") or {}

            parsed: dict[str, Any] | None = None
            parse_error = ""
            if not error and int(status_code or 0) == 200:
                try:
                    parsed = _parse_json_maybe(_extract_output_text(body))
                except Exception as exc:  # pragma: no cover - defensive
                    parse_error = str(exc)

            results[custom_id] = {
                "status_code": status_code,
                "error": error,
                "body": body,
                "parsed": parsed,
                "parse_error": parse_error,
            }
    return results


def _combined_score(priority_score: float, parsed: dict[str, Any] | None) -> float:
    if not parsed:
        return priority_score
    adjustment = int(parsed.get("priority_adjustment", 0) or 0)
    relabel = parsed.get("relabel_decision", "")
    relabel_bonus = {
        "label_priority": 6,
        "review": 0,
        "review_or_skip": -6,
    }.get(relabel, 0)
    playable_bonus = 3 if parsed.get("likely_playable") else -3
    return priority_score + adjustment + relabel_bonus + playable_bonus


def _write_merged_csv(rows: list[dict[str, str]], out_path: Path) -> None:
    if not rows:
        raise ValueError("No rows to write.")
    fieldnames = list(rows[0].keys())
    with out_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def _write_priority_csv(rows: list[dict[str, str]], out_path: Path) -> None:
    fieldnames = [
        "custom_id",
        "match_name",
        "frame_idx",
        "reason",
        "image_name",
        "priority_score",
        "priority_adjustment",
        "combined_priority_score",
        "relabel_decision",
        "detector_issue",
        "occlusion_level",
        "likely_playable",
        "visible_player_count",
        "confidence",
        "notes",
        "copied_path",
    ]
    with out_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow({key: row.get(key, "") for key in fieldnames})


def _write_markdown(rows: list[dict[str, str]], out_path: Path, merged_csv: Path, priority_csv: Path | None) -> None:
    total = len(rows)
    success = sum(1 for row in rows if row.get("batch_ok") == "true")
    decisions = Counter(row.get("relabel_decision", "") for row in rows if row.get("relabel_decision"))
    issues = Counter(row.get("detector_issue", "") for row in rows if row.get("detector_issue"))
    occlusion = Counter(row.get("occlusion_level", "") for row in rows if row.get("occlusion_level"))
    per_match = defaultdict(int)
    for row in rows:
        per_match[row.get("match_name", "")] += 1

    top_rows = sorted(
        rows,
        key=lambda row: (-float(row.get("combined_priority_score", "0") or 0), row.get("image_name", "")),
    )[:10]

    lines = [
        "# Track B OpenAI Batch QA Summary",
        "",
        "## Overview",
        "",
        f"- Requests merged: `{total}`",
        f"- Successful parsed QA rows: `{success}`",
        f"- Merged CSV: `{merged_csv}`",
    ]
    if priority_csv:
        lines.append(f"- Priority CSV: `{priority_csv}`")

    lines.extend(["", "## Relabel Decisions", ""])
    for label, count in decisions.most_common():
        lines.append(f"- `{label}`: `{count}`")

    lines.extend(["", "## Detector Issues", ""])
    for label, count in issues.most_common():
        lines.append(f"- `{label}`: `{count}`")

    lines.extend(["", "## Occlusion Levels", ""])
    for label, count in occlusion.most_common():
        lines.append(f"- `{label}`: `{count}`")

    lines.extend(["", "## Per-Match Rows", ""])
    for match_name, count in sorted(per_match.items()):
        lines.append(f"- `{match_name}`: `{count}`")

    lines.extend(
        [
            "",
            "## Top Priority Frames",
            "",
            "| Match | Frame | Combined Score | Decision | Issue | Note |",
            "| --- | ---: | ---: | --- | --- | --- |",
        ]
    )
    for row in top_rows:
        lines.append(
            "| {match} | {frame} | {score:.2f} | {decision} | {issue} | {note} |".format(
                match=row.get("match_name", ""),
                frame=row.get("frame_idx", ""),
                score=float(row.get("combined_priority_score", "0") or 0),
                decision=row.get("relabel_decision", ""),
                issue=row.get("detector_issue", ""),
                note=(row.get("notes", "") or "").replace("|", "/"),
            )
        )

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def run(args: argparse.Namespace) -> int:
    request_manifest = Path(args.request_manifest)
    batch_output = Path(args.batch_output)
    if not request_manifest.exists():
        raise FileNotFoundError(request_manifest)
    if not batch_output.exists():
        raise FileNotFoundError(batch_output)

    request_rows = _read_csv(request_manifest)
    results = _load_results(batch_output)

    merged_rows: list[dict[str, str]] = []
    for row in request_rows:
        custom_id = row["custom_id"]
        result = results.get(custom_id, {})
        parsed = result.get("parsed") or {}
        priority_score = float(row.get("priority_score", "0") or 0.0)
        combined = _combined_score(priority_score, parsed if isinstance(parsed, dict) else None)
        merged_rows.append(
            {
                **row,
                "batch_ok": "true" if parsed else "false",
                "status_code": str(result.get("status_code", "")),
                "parse_error": str(result.get("parse_error", "")),
                "priority_adjustment": str(parsed.get("priority_adjustment", "")) if parsed else "",
                "combined_priority_score": f"{combined:.2f}",
                "visible_player_count": str(parsed.get("visible_player_count", "")) if parsed else "",
                "likely_playable": str(parsed.get("likely_playable", "")).lower() if parsed else "",
                "occlusion_level": str(parsed.get("occlusion_level", "")) if parsed else "",
                "detector_issue": str(parsed.get("detector_issue", "")) if parsed else "",
                "relabel_decision": str(parsed.get("relabel_decision", "")) if parsed else "",
                "confidence": str(parsed.get("confidence", "")) if parsed else "",
                "notes": str(parsed.get("notes", "")) if parsed else "",
            }
        )

    merged_rows.sort(
        key=lambda row: (-float(row.get("combined_priority_score", "0") or 0), row.get("image_name", "")),
    )

    out_csv = Path(args.out_csv)
    out_csv.parent.mkdir(parents=True, exist_ok=True)
    _write_merged_csv(merged_rows, out_csv)

    priority_csv_path: Path | None = None
    if args.out_priority_csv:
        priority_csv_path = Path(args.out_priority_csv)
        priority_csv_path.parent.mkdir(parents=True, exist_ok=True)
        _write_priority_csv(merged_rows, priority_csv_path)

    out_md = Path(args.out_md)
    out_md.parent.mkdir(parents=True, exist_ok=True)
    _write_markdown(merged_rows, out_md, out_csv, priority_csv_path)

    print(f"rows: {len(merged_rows)}")
    print(f"merged_csv: {out_csv}")
    if priority_csv_path:
        print(f"priority_csv: {priority_csv_path}")
    print(f"summary_md: {out_md}")
    return 0


def main() -> None:
    parser = argparse.ArgumentParser(description="Summarize OpenAI Batch frame QA results for Track B.")
    parser.add_argument("--request-manifest", required=True, help="Manifest CSV from build_track_b_openai_batch.py")
    parser.add_argument("--batch-output", required=True, help="Downloaded Batch API output .jsonl file")
    parser.add_argument("--out-csv", required=True, help="Merged per-frame QA CSV path")
    parser.add_argument("--out-md", required=True, help="Markdown summary output path")
    parser.add_argument("--out-priority-csv", default="", help="Optional sorted relabel priority CSV path")
    raise SystemExit(run(parser.parse_args()))


if __name__ == "__main__":
    main()
